clean:
	gradle clean
build:
	gradle clean build
install:
	build/install/app/bin/app src/test/resources/file1.json src/test/resources/file2.json
run-dist:
	build/install/app/bin/app src/test/resources/file1.json src/test/resources/file2.json
run:
	build/install/app/bin/app src/test/resources/file1.json src/test/resources/file2.json

.PHONY: build

